package com.ablhds.app.domain;

/**
 * Códigos de erro de validação e processamento
 */
public enum Erro {
    CPF_INVALIDO,
    NOME_INVALIDO,
    DATA_INVALIDA,
    CLIENTE_MENOR_DE_IDADE,
    CPF_JA_EXISTENTE,
    LOGRADOURO_INVALIDO,
    NUMERO_INVALIDO,
    COMPLEMENTO_INVALIDO,
    BAIRRO_INVALIDO,
    CIDADE_INVALIDA,
    CEP_INVALIDO,
    UF_INVALIDA,
    DDD_INVALIDO,
    NUMERO_TEL_INVALIDO,
    ENDERECO_INVALIDO,
    TELEFONE_INVALIDO,
    ERRO_BD,

    VEICULO_PLACA_INVALIDA,
    VEICULO_PLACA_DUPLICADA,
    VEICULO_MODELO_INVALIDO,
    VEICULO_COR_INVALIDA,
    VEICULO_ANO_INVALIDO,
    VEICULO_DIARIA_INVALIDA,
    VEICULO_QUILOMETRAGEM_INVALIDA,

    //TODO - Criar mais erros para locação
    CLIENTE_INEXISTENTE,
    VEICULO_JA_ALOCADO,
    LOCACAO_INVALIDA,
    VEICULO_INEXISTENTE,

}
